### ISSUE TITLE
FreeRTOS SMP not receiving semaphore to commit due to while loop getting optimized out

### ISSUE THREAD

**Issue by alealfaro16** [jondurrant/RPIPicoOnboardNVS#1]
https://github.com/jondurrant/RPIPicoOnboardNVS/blob/4736d72d0743c33d1688683904e8232e50bbc7c4/src/NVSAgent.cpp#L152
https://github.com/jondurrant/RPIPicoOnboardNVS/blob/4736d72d0743c33d1688683904e8232e50bbc7c4/src/NVSAgent.cpp#L138
xCore1Resume and xCore1Paused should be volatile variables. Compiler will optimize them out and make a while(true) instead. Then whenever there's an attempt to commit these loops will never exit and xSemaphoreTake will timeout and that commit will not be done.

I tested the change and it works.

**Comment by jondurrant** [comment]
Thank you. Nice catch.

**Comment by jondurrant** [comment]
Fixed. Thank you for finding this one @alealfaro16 and providing the fix. Appreciated.
